// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tqsqfwddzdwepnbbbyie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxc3Fmd2RkemR3ZXBuYmJieWllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5Njc2NTgsImV4cCI6MjA2MDU0MzY1OH0.hvG_3euZA8ACTU3d1GMq3EeJycB9kWqgzssw9-rwLbY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);